/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.service;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface Calc {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Calc\",\"namespace\":\"avro.service\",\"types\":[],\"messages\":{\"add\":{\"request\":[{\"name\":\"i\",\"type\":\"double\"},{\"name\":\"j\",\"type\":\"double\"}],\"response\":\"double\"},\"minus\":{\"request\":[{\"name\":\"i\",\"type\":\"double\"},{\"name\":\"j\",\"type\":\"double\"}],\"response\":\"double\"}}}");
  double add(double i, double j) throws org.apache.avro.AvroRemoteException;
  double minus(double i, double j) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends Calc {
    public static final org.apache.avro.Protocol PROTOCOL = avro.service.Calc.PROTOCOL;
    void add(double i, double j, org.apache.avro.ipc.Callback<java.lang.Double> callback) throws java.io.IOException;
    void minus(double i, double j, org.apache.avro.ipc.Callback<java.lang.Double> callback) throws java.io.IOException;
  }
}